## Sikit-Learn 라이브러리  

- 머신러닝을 다루는 다양한 라이브러리가 있습니다.
- Tensorflow, Keras, Pytorch, Sikit-Learn


In [ ]:
%pip install scikit-learn==1.0.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 37.1 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 0.23.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.0.2 which is incompatible.


In [ ]:
import sklearn
print(sklearn.__version__)

1.0.2


In [ ]:
# Classification - 분류 알고리즘을 사용해서 꽃의 종류를 구분을 해보도록 하겠습니다.
from sklearn.datasets import load_iris
import pandas as pd

In [ ]:
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
iris = load_iris()

iris.data #feature

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
iris.target #label data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# 1. 준비되어있는 데이터셋을 나눈다. (1) 학습용 데이터(train_data) (2) 테스터용 데이터 (test_data)
# train_test_split() -> 학습용 데이터셋과 테스트용 데이터 셋으로 분리하는 역활

from sklearn.model_selection import train_test_split

train_test_split(iris.data, iris.target, test_size=0.2, random_state=123)

[array([[7.4, 2.8, 6.1, 1.9],
        [6. , 2.2, 5. , 1.5],
        [4.7, 3.2, 1.6, 0.2],
        [5.1, 3.5, 1.4, 0.2],
        [6. , 2.2, 4. , 1. ],
        [5. , 2.3, 3.3, 1. ],
        [7.9, 3.8, 6.4, 2. ],
        [5.4, 3.9, 1.7, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.8, 2.7, 3.9, 1.2],
        [5. , 2. , 3.5, 1. ],
        [5. , 3.2, 1.2, 0.2],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3. , 5.2, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [5.8, 2.8, 5.1, 2.4],
        [6.3, 3.4, 5.6, 2.4],
        [5.5, 2.3, 4. , 1.3],
        [5.1, 3.8, 1.5, 0.3],
        [4.4, 3. , 1.3, 0.2],
        [6.5, 3.2, 5.1, 2. ],
        [5.1, 3.3, 1.7, 0.5],
        [4.9, 3.1, 1.5, 0.1],
        [6.7, 3.1, 4.7, 1.5],
        [6.1, 3. , 4.6, 1.4],
        [5.5, 2.5, 4. , 1.3],
        [5.7, 2.6, 3.5, 1. ],
        [5.8, 2.7, 5.1, 1.9],
        [6.7, 3.1, 4.4, 1.4],
        [6.4, 3.2, 5.3, 2.3],
        [4.5, 2.3, 1.3, 0.3],
        [6.7, 3.3, 5.7, 2.1],
        [5.7, 3. , 4.2, 1.2],
        [5

In [ ]:
# X_train : 학습용 피처데이터, X_test : 테스트용 피쳐 데이터
# y_train : 학습용 레이블 데이터, y_train : 테스트용 레이블 데이터

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=123)

In [ ]:
print(len(y_test), len(y_train))

y_test, y_train


30 120


(array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
        0, 2, 0, 0, 0, 2, 2, 0]),
 array([2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 2, 0,
        0, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 0, 0, 2, 1, 2, 2, 0, 1, 1, 2, 0,
        2, 1, 1, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 0, 1, 2, 0, 2, 0, 0, 1,
        0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0,
        0, 1, 2, 2, 2, 2, 0, 1, 0, 1, 1, 0, 1, 2, 1, 2, 2, 0, 1, 0, 2, 2,
        1, 1, 2, 2, 1, 0, 1, 1, 2, 2]))

In [ ]:
# 2. 학습을 위한 알고리즘 불러옵니다.

from sklearn.tree import DecisionTreeClassifier # 분류 알고리즘 (supervise learining)

dt_clf = DecisionTreeClassifier(random_state=123)
dt_clf

DecisionTreeClassifier(random_state=123)

In [ ]:
# 3. 학습을 진행합니다. => train_data( X_train, y_train)
dt_clf.fit(X_train, y_train) # fit() - 학습을 진행

DecisionTreeClassifier(random_state=123)

In [ ]:
X_test

array([[6.3, 2.5, 4.9, 1.5],
       [6.8, 3. , 5.5, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [5.6, 3. , 4.1, 1.3],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 3. , 4.8, 1.8],
       [6.3, 2.3, 4.4, 1.3],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.9, 3.1, 5.1, 2.3],
       [5.5, 4.2, 1.4, 0.2],
       [5.2, 2.7, 3.9, 1.4],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3. , 6.1, 2.3],
       [6.5, 3. , 5.8, 2.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.1, 2.9, 4.7, 1.4],
       [4.8, 3. , 1.4, 0.3],
       [5.2, 3.4, 1.4, 0.2],
       [6.3, 2.8, 5.1, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5.1, 3.8, 1.6, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 3.8, 6.7, 2.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
# 4. 시험을 치러갑니다. => test_data(X_test, y_test) // 수능시험
# predict() => 예측해봐

predict = dt_clf.predict(X_test) # 테스트

In [ ]:
predict

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0])

In [ ]:
y_test

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0])

In [ ]:
# 5. 채점을 진행합니다.
# accuracy_score()

from sklearn.metrics import accuracy_score

accuracy_score(y_test, predict)  #정답과 실제 알고리즘이 풀이하는 정답율

0.9666666666666667

In [ ]:
df = pd.DataFrame(data=X_test, columns=iris.feature_names)

df['answer'] = y_test
df['predict'] = predict

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 6.3               2.5                4.9               1.5   
1                 6.8               3.0                5.5               2.1   
2                 6.4               2.8                5.6               2.2   
3                 5.6               3.0                4.1               1.3   
4                 4.9               3.6                1.4               0.1   
5                 6.0               3.0                4.8               1.8   
6                 6.3               2.3                4.4               1.3   
7                 4.4               3.2                1.3               0.2   
8                 4.4               2.9                1.4               0.2   
9                 5.5               2.6                4.4               1.2   
10                6.9               3.1                5.1               2.3   
11                5.5               4.2                1.4               0.2   
12                5.2               2.7                3.9               1.4   
13                6.5               3.0                5.5               1.8   
14                7.7               3.0                6.1               2.3   
15                6.5               3.0                5.8               2.2   
16                5.5               3.5                1.3               0.2   
17                4.3               3.0                1.1               0.1   
18                6.1               2.9                4.7               1.4   
19                4.8               3.0                1.4               0.3   
20                5.2               3.4                1.4               0.2   
21                6.3               2.8                5.1               1.5   
22                4.8               3.4                1.9               0.2   
23                6.1               3.0                4.9               1.8   
24                5.1               3.8                1.6               0.2   
25                5.4               3.4                1.7               0.2   
26                5.4               3.4                1.5               0.4   
27                5.6               2.8                4.9               2.0   
28                7.7               3.8                6.7               2.2   
29                5.0               3.6                1.4               0.2   

    answer  predict  
0        1        1  
1        2        2  
2        2        2  
3        1        1  
4        0        0  
5        2        1  
6        1        1  
7        0        0  
8        0        0  
9        1        1  
10       2        2  
11       0        0  
12       1        1  
13       2        2  
14       2        2  
15       2        2  
16       0        0  
17       0        0  
18       1        1  
19       0        0  
20       0        0  
21       2        2  
22       0        0  
23       2        2  
24       0        0  
25       0        0  
26       0        0  
27       2        2  
28       2        2  
29       0        0

In [ ]:
fd=urus = load_iris()
dt_clf = DecisionTreeClassifier()

dt_clf.fit(iris.data, iris.target)

pred = dt_clf.predict(iris.data)

accuracy_score(iris.target, pred)

1.0

## 5. Scikit-Learn 라이브러리 심화

### (1) 교차 검증

- 교차 검증은 훈련 세트와 테스트 세트를 다양하게 만들어서 모델의 성능을 더 정확하고 신뢰성 있게 평가할 수 있도록 돕는 역할을 한다.
- 학습 데이터 세트 ⇒ 학습 데이터 세트 + 검증 데이터 세트로 분리
    - 검증 데이터 세트를 모의고사라고 볼 수 있다.
- 테스트 데이터 세트 ⇒ 모델 학습 및 검증 후 최종적으로 성능을 평가하기 위한 데이터 세트
    - 수능 시험

**K-Fold 교차 검증**

**(1) 일반 K-Fold**

- K개의 데이터 폴드 세트를 만들어서
⇒ K번만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행하는 방법

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/716fd3f2-5491-493a-9c0b-6afcd6439bbf/Untitled.png)

- 검증 → 학습 → 학습 → 학습 → 학습
- K = N
    - N번의 학습과 검증 수행

```python
from sklearn.model_selection import KFold
```

- K-Fold 예제 코드
    
    ```python
    import numpy as np
    from sklearn.datasets import load_iris
    from sklearn.model_selection import KFold
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.metrics import accuracy_score
    ```
    
    ```python
    # 데이터 로드
    iris = load_iris()
    train_data = iris.data
    train_target = iris.target
    ```
    
    ```python
    # 모델 학습 및 평가 함수 정의
    def train_and_evaluate(train_index, test_index, model, train_data, train_target):
      # 학습 및 검증 데이터 분리
      X_train, X_test = train_data[train_index], train_data[test_index]
      y_train, y_test = train_target[train_index], train_target[test_index]
    
      # 모델 학습 및 예측
      model.fit(X_train, y_train)
      predictions = model.predict(X_test)
    
      # 정확도 계산
      accuracy = accuracy_score(y_test, predictions)
      return accuracy, X_train.shape[0], X_test.shape[0], test_index
    ```
    
    ```python
    # KFold 교차 검증 설정
    kfold = KFold(n_splits=5)
    cv_accuracy = []
    dt_clf = DecisionTreeClassifier()
    ```
    
    ```python
    # KFold 교차 검증 수행
    for fold, (train_index, test_index) in enumerate(kfold.split(train_data), 1):
      accuracy, train_size, test_size, test_idx = train_and_evaluate(
          train_index, test_index, dt_clf, train_data, train_target
      )
      cv_accuracy.append(accuracy)
    
      print(f"{fold}번째 트레이닝")
      print(f"검증 정확도: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
      print(f"검증 데이터 셋 인덱스 값: {test_idx}")
      print(f"===" * 10)
    
    # 최종 정확도 평균 출력
    print("최종 정확도 평균 값: ", np.mean(cv_accuracy))
    ```
    

---

**(2) Stratified K 폴드**

- 불균형한 데이터셋에서 사용
- 불균형한 데이터 셋에서의 학습/검증 평가를 반복하기 위해 사용
    - 1만건의 데이터 세트 중 10건만이 정답인 경우 학습 데이터와 테스트 데이터 세트를 분리해내는 데 한계가 생김
    - 공정 데이터 10만건 중 오류가 발생한 데이터가 10건
    
- Stratified 예제 코드
    
    ```python
    import numpy as np
    from sklearn.datasets import load_iris
    from sklearn.model_selection import StratifiedKFold
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.metrics import accuracy_score
    ```
    
    ```python
    # iris 데이터 셋 로드
    
    iris = load_iris()
    features = iris.data
    label = iris.target
    ```
    
    ```python
    # 모델 초기화
    dt_clf = DecisionTreeClassifier(random_state=156)
    ```
    
    ```python
    # Stratified KFold 교차 검증 설정
    skfold = StratifiedKFold(n_splits=3)
    cv_accuracy = []
    ```
    
    ```python
    # Stratified KFold 교차 검증 수행
    
    for fold, (train_index, test_index) in enumerate(skfold.split(features, label), 1):
      accuracy, train_size, test_size, test_idx = train_and_evaluate(
          train_index, test_index, dt_clf, features, label
      )
      cv_accuracy.append(accuracy)
    
      # 출력 메세지 변경
      print(f"{fold}번째 트레이닝")
      print(f"검증 정확도: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
      print(f"검증 데이터 셋 인덱스 값: {test_idx}")
      print("===" * 10)
    
    # 교차 검증 별 정확도 및 평균 정확도 계산
    print("\n최종 정확도 평균 값:", np.mean(cv_accuracy))
    
    최종 정확도 평균 값: 0.9666666666666666
    ```
    

---

**(3) cross_val_score()**

- 교차 검증을 쉽게 도와주는 함수

- cross_val_score 예제코드
    
    ```python
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.model_selection import cross_val_score
    from sklearn.datasets import load_iris
    import numpy as np
    
    iris_data = load_iris()
    dt_clf = DecisionTreeClassifier(random_state=156)
    
    data = iris_data.data
    label = iris_data.target
    
    scores = cross_val_score(dt_clf, data, label, scoring="accuracy", cv=5)
    
    print("교차 검증 별 정확도: ", np.round(scores, 5))
    print("평균 검증 정확도: ", np.round(np.mean(scores), 5))
    
    교차 검증 별 정확도:  [0.96667 0.96667 0.9     0.96667 1.     ]
    평균 검증 정확도:  0.96
    ```
    

### (2) 피처 엔지니어링(Feature Engineering)

- 머신러닝 알고리즘 학습에 용이한 데이터로 변경하는 과정
- 데이터를 정제하고 변환하여 모델이 패턴을 쉽게 인식하고 학습할 수 있도록 돕는다.

1. **숫자형 데이터로 변환**:
    
    대부분의 머신 러닝 모델은 숫자형 데이터를 입력으로 사용합니다. 따라서 문자열 데이터를 숫자로 변환하는 작업이 필요할 수 있습니다. 이를 위해 원-핫 인코딩, 레이블 인코딩, 범주형 특성을 숫자형으로 매핑하는 작업 등이 사용될 수 있습니다.
    
2. **누락된 데이터 처리**:
    
    데이터에서 누락된 값을 채우거나 해당 데이터 행 또는 열을 삭제할 수 있습니다. 이를 통해 모델이 더 나은 예측을 수행할 수 있도록 데이터를 정리할 수 있습니다.
    
3. **새로운 특성 생성**:
    
    기존 특성을 기반으로 새로운 특성을 만들어 모델에 추가할 수 있습니다. 예를 들어, 날짜 데이터에서 요일, 월, 연도 등의 정보를 추출하여 새로운 특성으로 사용할 수 있습니다.
    
4. **표준화 및 정규화**:
    
    데이터의 스케일을 조정하여 모델이 더 잘 동작하도록 만들 수 있습니다. 주로 연속형 숫자 특성을 표준화(평균 0, 표준 편차 1)하거나 정규화(0과 1 사이로 스케일 조정)하는 작업이 포함됩니다.
    
5. **이상치 처리**:
    
    이상치(outliers)는 모델의 성능을 왜곡시킬 수 있으므로 이를 식별하고 처리하는 것이 중요합니다. 이상치를 제거하거나 대체하는 방법을 사용할 수 있습니다.
    
6. **특성 선택**:
    
    중요한 특성을 선택하고 불필요한 특성을 제거함으로써 모델의 복잡성을 줄이고 성능을 향상시킬 수 있습니다.
    
7. **데이터 스케일링:**
다양한 특성(feature)들의 값 범위를 조정하여 모델의 성능을 향상시킵니다. 대표적인 방법으로는 정규화(normalization)나 표준화(standardization)가 있습니다.
8. **범주형 데이터 인코딩:**
범주형 변수들을 숫자 형태로 변환합니다. 원-핫 인코딩(One-hot encoding)이나 레이블 인코딩(Label encoding) 등이 사용됩니다.
    1. 데이터 카테고리를 숫자로 변경한다.
    2. 카테고리: 초등학생, 중학생, 고등학생, 대학생 ⇒ 0, 1, 2, 3 ⇒ 0.1, 0.2, 0.3
        - 단, 이 경우 특정 알고리즘에서는 큰 값이 좋다라는 잘못된 인식을 할 수가 있다.
            - ex) 냉장고 부피가 100, 컵의 부피가 10

### (3) **데이터 인코딩**

1. **레이블 인코딩**
- 머신러닝에서 학습을 위한 데이터는 숫자형이어야 함. (문자열 데이터를 입력 받지 않음)
    
    ![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/0590e0ec-c999-4668-996b-6528b941ac3a/Untitled.png)
    
- 알고리즘에 따라서는 값에 따른 숫자 크기의 차이가 영향을 미칠 수 있음.

1. **원-핫 인코딩**
    
    ![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/91befdd0-8d27-40a9-b1c8-6de29b930cde/Untitled.png)
    
- 해당 컬럼에 속하는 값만 1로 생성하고 나머지는 0으로 변경.

**pd.get_dummies**

- 범주형 데이터를 원-핫 인코딩(one-hot encoding)하는 방법 중 하나

```python
import pandas as pd

data = {'Fruit': ['Apple', 'Banana', 'Cherry', 'Apple', 'Cherry'],
        'Color': ['Red', 'Yellow', 'Red', 'Green', 'Red']}
df = pd.DataFrame(data)
df_encoded = pd.get_dummies(df, columns=['Fruit', 'Color'], prefix=['Fruit', 'Color'])
```

### (4) Overfitting과 Underfitting

Overfitting: 과대적합(과적합)

- 훈련 데이터를 과도하게 학습을 하는 경우에 발생 (⇒모델의 복잡도 증가)
- 학습에서의 성능 평가는 높게 나올 수 있으나, 실전에 사용하기에는 어려움이 있음.

Underfitting: 과소적합

- 모델이 학습할 여지가 더 남아 있는 상태

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/4e9fc5fc-84d0-4a89-ad94-9c5aca91eb94/Untitled.png)

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/9f8de3ae-6311-4331-af32-3c3869361a81/Untitled.png)

*Epochs: 전체 데이터셋 학습 횟수

*Loss(RMSE): 예측 모델에서 예측한 값과 실제 값 사이의 평균 차이를 측정(작을수록 유사)

*Validation(실제 데이터)

**발생이유:**

- 인공지능은? ⇒ 내가 수집하고, 전처리한 데이터를 인공지능에게 학습시키는 과정이 포함됨 (최적화)
- 훈련 데이터 세트로 학습했을 때의 성능도 중요하지만 실전에서의 성능도 중요함.
- 훈련 데이터에 최적화 되는 것과 실전에 다양하게 사용될 수 있도록 일반화되는 것 사이에서 줄다리기

**결론:**

- 문제의 본질은 데이터. 훈련 데이터와 실전 데이터가 비슷하다면 오버피팅 문제가 발생하지 않겠죠.
- 너무 훈련 데이터에 집착을 하다보면 실전 상황에서의 대응이 힘들어질 수 있다.

**해결방법:**

- Training data(input data) - DA(Data augmentation)
    - 갖고 있는 데이터셋을 여러 가지 방법으로 augment하여 실질적인 학습 데이터셋의 규모를 키울 수 있는 방법
    - 원래 이미지 한장을 ⇒ 크롭을 한다던지, RGB 색상을 변경한다던지, 회전을 시킨다던지
- Loss Function / Optimizer - L2 regularization
    - loss function에 패널티를 줘서 Optimer 포인트까지 가는 것을 막을 수도 있다.
- Target values - DisturbLabel
    - 의도적으로 틀린 답을 알려주는 방법
- Sampling - Weighted random sampling
    - 각 target의 갯수를 맞춰주는 방법
- Learning approach - Semi-supervised learning
    - target값이 없던 데이터를 가져와서 target값을 채워놓고 ⇒ 다시 이 데이터를 추가 후 학습 진행 ⇒ 반복..

### (5) 실습 - 타이타닉 생존자 예측 / GermanCredit

[[실습] 타이타닉 생존자 예측](https://www.notion.so/80a7e441154b4954a96a25e99963f71f?pvs=21)

[[실습] 독일인 신용 예측 모델](https://www.notion.so/2318996a9c2a49ed99cf5452e0a46d1e?pvs=21)

## 교차 검증
- (1) K Fold 검증  
- (2) Stratified 검증  
- (3) cross_val_score() => 검증을 쉽게 할 수 있도록 도와주는 함수  


In [1]:
#- (1) K Fold 검증

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 데이터 로드
iris = load_iris()
train_data = iris.data
train_target = iris.target


# 모델 학습 및 평가 함수 정의
def train_and_evaluate(train_index, test_index, model, train_data, train_target):
  # 학습 및 검증 데이터 분리
  X_train, X_test = train_data[train_index], train_data[test_index]
  y_train, y_test = train_target[train_index], train_target[test_index]

  # 모델 학습 및 예측
  model.fit(X_train, y_train)
  predictions = model.predict(X_test)

  # 정확도 계산
  accuracy = accuracy_score(y_test, predictions)
  return accuracy, X_train.shape[0], X_test.shape[0], test_index


  # KFold 교차 검증 설정
kfold = KFold(n_splits=5)
cv_accuracy = []
dt_clf = DecisionTreeClassifier()

# KFold 교차 검증 수행
for fold, (train_index, test_index) in enumerate(kfold.split(train_data), 1):
  accuracy, train_size, test_size, test_idx = train_and_evaluate(
      train_index, test_index, dt_clf, train_data, train_target
  )
  cv_accuracy.append(accuracy)


  print(f"{fold}번째 트레이닝")
  print(f"검증 정확도: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
  print(f"검증 데이터 셋 인덱스 값: {test_idx}")
  print(f"===" * 10)

# 최종 정확도 평균 출력
print("최종 정확도 평균 값: ", np.mean(cv_accuracy))

1번째 트레이닝
검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2번째 트레이닝
검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
3번째 트레이닝
검증 정확도: 0.8666666666666667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
4번째 트레이닝
검증 정확도: 0.9333333333333333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
5번째 트레이닝
검증 정확도: 0.7333333333333333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
최종 정확도 평균 값:  0.9066666666666666


In [3]:
# - (2) Stratified 검증

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# iris 데이터 셋 로드

iris = load_iris()
features = iris.data
label = iris.target

# 모델 초기화
dt_clf = DecisionTreeClassifier(random_state=156)

# Stratified KFold 교차 검증 설정
skfold = StratifiedKFold(n_splits=3)
cv_accuracy = []

# Stratified KFold 교차 검증 수행

for fold, (train_index, test_index) in enumerate(skfold.split(features, label), 1):
  accuracy, train_size, test_size, test_idx = train_and_evaluate(
      train_index, test_index, dt_clf, features, label
  )
  cv_accuracy.append(accuracy)

  # 출력 메세지 변경
  print(f"{fold}번째 트레이닝")
  print(f"검증 정확도: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
  print(f"검증 데이터 셋 인덱스 값: {test_idx}")
  print("===" * 10)

# 교차 검증 별 정확도 및 평균 정확도 계산
print("\n최종 정확도 평균 값:", np.mean(cv_accuracy))



1번째 트레이닝
검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2번째 트레이닝
검증 정확도: 0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3번째 트레이닝
검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

최종 정확도 평균 값: 0.9666666666666667


In [5]:
#- (3) cross_val_score() => 검증을 쉽게 할 수 있도록 도와주는 함수

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
import numpy as np

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

scores = cross_val_score(dt_clf, data, label, scoring="accuracy", cv=5)

print("교차 검증 별 정확도: ", np.round(scores, 5))
print("평균 검증 정확도: ", np.round(np.mean(scores), 5))



교차 검증 별 정확도:  [0.96667 0.96667 0.9     0.96667 1.     ]
평균 검증 정확도:  0.96


# 데이터 인코딩
1. Label Encoding
2. OneHot Encoding
3. GetDeummies - pd의 df를 활용한 방법

In [9]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder

items=['강남구', '서초구', '송파구', '노원구', '마포구', '마포구', '용산구', '용산구']

# LabelEncoder 를 객체로 생성한 후, fit() 과 transform() 으로 label 인코딩 수행.

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print('인코딩 반환값:', labels) #문자열 값 -> 숫자형 값으로 변경 (Label Encoding)

인코딩 반환값: [0 3 4 1 2 2 5 5]


In [12]:
# OneHot Encoding

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['강남구', '서초구', '송파구', '노원구', '마포구', '마포구', '용산구', '용산구']

# 2차원 ndarray로 변환합니다.
# reshape() 함수의 첫 번째 인자로 -1을 주면 해당 차원의 크기를 자동으로 계산하여 맞춰줍니다.
# 두 번째 인자로 1을 주면 열의 크기를 1로 지정하여 겨과적으로 1개의 열로 이루어진 2차원 배열을 생성합니다.
# 이러게 2차원 배열로 반환된 데이터는 머신 러닝 모델에 입력으로 사용하기에 적합한 형태가 됩니다.
# 머신 러닝 모델은 입력으로 2차원 배열을 기대하므로, 데이터를 이와 같은 형태로 변호나하여 모델에 사용해야 합니다.

items = np.array(items).reshape(-1,1)

#원-핫 인코딩을 적용합니다.
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

# OneHotEncoder로 반환한 결과는 희소행렬(Sparse Matrix)이므로 toarray()를 이용하여 밀집 행렬(Dense Matrix)로 변환.
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)



원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [13]:
# GetDeummies - pd의 df를 활용한 방법

import pandas as pd


df = pd.DataFrame({'item':['강남구', '서초구', '송파구', '노원구', '마포구', '마포구', '용산구', '용산구']})

pd.get_dummies(df)

item_강남구  item_노원구  item_마포구  item_서초구  item_송파구  item_용산구
0         1         0         0         0         0         0
1         0         0         0         1         0         0
2         0         0         0         0         1         0
3         0         1         0         0         0         0
4         0         0         1         0         0         0
5         0         0         1         0         0         0
6         0         0         0         0         0         1
7         0         0         0         0         0         1

In [15]:
import pandas as pd

data = {'Fruit': ['Apple', 'Banana', 'Cherry', 'Apple', 'Cherry'],
        'Color': ['Red', 'Yellow', 'Red', 'Green', 'Red']}
df = pd.DataFrame(data)
df


Fruit   Color
0   Apple     Red
1  Banana  Yellow
2  Cherry     Red
3   Apple   Green
4  Cherry     Red

In [17]:
import pandas as pd

data = {'Fruit': ['Apple', 'Banana', 'Cherry', 'Apple', 'Cherry'],
        'Color': ['Red', 'Yellow', 'Red', 'Green', 'Red']}
df = pd.DataFrame(data)
pd.get_dummies(df, columns=['Fruit', 'Color'], prefix=['Fruit', 'Color'])

Fruit_Apple  Fruit_Banana  Fruit_Cherry  Color_Green  Color_Red  \
0            1             0             0            0          1   
1            0             1             0            0          0   
2            0             0             1            0          1   
3            1             0             0            1          0   
4            0             0             1            0          1   

   Color_Yellow  
0             0  
1             1  
2             0  
3             0  
4             0